sources_path : "src/"
index_path: src/en/index.html
netlify_site_name : cranky-noyce-482b5f
production_branch : master
editable_selector : ".editable ul, .editable h1,.editable h2,.editable h3,.editable h4,.editable h5,.editable p,.editable a,.editable button, nav a"
has_components : false