backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

collections:
  - name: 'Blog EN' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    file: 'data/blog_en.json'
    fields:
      - label: Posts
        name: posts
        widget: list
        fields:
          - { label: Date, name: date, widget: date }
          - { label: Title, name: title, widget: string }
          - {
              label: Slug,
              name: slug,
              widget: string,
              pattern: ['^\S*$', 'Must not contains spaces'],
            }
          - { label: Thumbnail, name: thumbnail, widget: image }
          - { label: Body, name: body, widget: markdown }

          

  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    files:
      - label: 'English posts'
        name: 'en-posts'
        file: 'data/blog_en.json'
        fields:
          - label: Posts
            name: posts
            widget: list
            fields:
              - { label: Date, name: date, widget: date }
              - { label: Title, name: title, widget: string }
              - {
                  label: Slug,
                  name: slug,
                  widget: string,
                  pattern: ['^\S*$', 'Must not contains spaces'],
                }
              - { label: Thumbnail, name: thumbnail, widget: image }
              - { label: Body, name: body, widget: markdown }

      - label: 'French posts'
        name: 'fr-posts'
        file: 'data/blog_fr.json'
        fields:
          - label: Posts
            name: posts
            widget: list
            fields:
              - { label: Date, name: date, widget: date }
              - { label: Title, name: title, widget: string }
              - {
                  label: Slug,
                  name: slug,
                  widget: string,
                  pattern: ['^\S*$', 'Must not contains spaces'],
                }
              - { label: Thumbnail, name: thumbnail, widget: image }
              - { label: Body, name: body, widget: markdown }

      - label: 'Italian posts'
        name: 'it-posts'
        file: 'data/blog_it.json'
        fields:
          - label: Posts
            name: posts
            widget: list
            fields:
              - { label: Date, name: date, widget: date }
              - { label: Title, name: title, widget: string }
              - {
                  label: Slug,
                  name: slug,
                  widget: string,
                  pattern: ['^\S*$', 'Must not contains spaces'],
                }
              - { label: Thumbnail, name: thumbnail, widget: image }
              - { label: Body, name: body, widget: markdown }

      - label: 'Spanish posts'
        name: 'es-posts'
        file: 'data/blog_es.json'
        fields:
          - label: Posts
            name: posts
            widget: list
            fields:
              - { label: Date, name: date, widget: date }
              - { label: Title, name: title, widget: string }
              - {
                  label: Slug,
                  name: slug,
                  widget: string,
                  pattern: ['^\S*$', 'Must not contains spaces'],
                }
              - { label: Thumbnail, name: thumbnail, widget: image }
              - { label: Body, name: body, widget: markdown }

  - name: 'languages'
    label: 'Languages'
    files:
      - label: 'Italian'
        name: 'it'
        file: 'data/strings_it.json'
        fields:
          - { name: index_1_title_1_1, widget: string }
          - { name: index_1_title_1_2, widget: string }
      - label: 'English'
        name: 'en'
        file: 'data/strings_en.json'
        fields:
          - { name: index_1_title_1_1, widget: string }
          - { name: index_1_title_1_2, widget: string }
      - label: 'French'
        name: 'fr'
        file: 'data/strings_fr.json'
        fields:
          - { name: index_1_title_1_1, widget: string }
          - { name: index_1_title_1_2, widget: string }
      - label: 'Spanish'
        name: 'es'
        file: 'data/strings_es.json'
        fields:
          - { name: index_1_title_1_1, widget: string }
          - { name: index_1_title_1_2, widget: string }

  - name: 'banner'
    label: 'Banner'
    files:
      - label: 'Italian messages'
        name: 'it'
        file: 'data/banner_it.json'
        fields:
          - label: Messages
            name: messages
            widget: list
            fields:
              - { name: title, widget: string }
              - { name: link, widget: string }
      - label: 'English messages'
        name: 'en'
        file: 'data/banner_en.json'
        fields:
          - label: Messages
            name: messages
            widget: list
            fields:
              - { name: title, widget: string }
              - { name: link, widget: string }
      - label: 'French messages'
        name: 'fr'
        file: 'data/banner_fr.json'
        fields:
          - label: Messages
            name: messages
            widget: list
            fields:
              - { name: title, widget: string }
              - { name: link, widget: string }
      - label: 'Spanish messages'
        name: 'es'
        file: 'data/banner_es.json'
        fields:
          - label: Messages
            name: messages
            widget: list
            fields:
              - { name: title, widget: string }
              - { name: link, widget: string }

media_folder: 'src/images/uploads'

public_folder: 'images/uploads'
