backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

strings_names: &language_strings
  - { name: index_1_title_1_1, widget: string }
  - { name: index_1_title_1_2, widget: string }

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    files:
      - label: 'Italian'
        name: 'it'
        file: 'data/strings_it.json'
        fields:
          - label: Posts
            name: posts
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Thumbnail, name: thumbnail, widget: image}
              - {label: Body, name: body, widget: markdown}

  - name: 'languages'
    label: 'Languages'    
    files:
      - label: 'Italian'
        name: 'it'
        file: 'data/strings_it.json'
        fields:
          <<: *language_strings
      - label: 'English'
        name: 'en'
        file: 'data/strings_en.json'
        fields:
          <<: *language_strings
      - label: 'French'
        name: 'fr'
        file: 'data/strings_fr.json'
        fields:
          <<: *language_strings
      - label: 'Spanish'
        name: 'es'
        file: 'data/strings_es.json'
        fields:
          <<: *language_strings
         

media_folder: 'src/images/uploads'

public_folder: 'images/uploads'
