backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    files:
      - label: 'Posts'
        name: 'it'
        file: 'data/blog.json'
        fields:
          - label: Posts
            name: posts
            widget: list
            fields:
              - { label: Date, name: date, widget: date }
              - { label: Title, name: title, widget: string }
              - { label: Thumbnail, name: thumbnail, widget: image }
              - { label: Body, name: body, widget: markdown }




  - name: 'languages'
    label: 'Languages'
    files:
      - label: 'Italian'
        name: 'it'
        file: 'data/strings_it.json'
        fields:
          - { name: index_1_title_1_1, widget: string }
          - { name: index_1_title_1_2, widget: string }
      - label: 'English'
        name: 'en'
        file: 'data/strings_en.json'
        fields:
          - { name: index_1_title_1_1, widget: string }
          - { name: index_1_title_1_2, widget: string }
      - label: 'French'
        name: 'fr'
        file: 'data/strings_fr.json'
        fields:
          - { name: index_1_title_1_1, widget: string }
          - { name: index_1_title_1_2, widget: string }
      - label: 'Spanish'
        name: 'es'
        file: 'data/strings_es.json'
        fields:
          - { name: index_1_title_1_1, widget: string }
          - { name: index_1_title_1_2, widget: string }

media_folder: 'src/images/uploads'

public_folder: 'images/uploads'
