backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

collections:
  - name: 'blog-en' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog EN' # Used in the UI
    folder: 'data/posts_en/'
    format: 'json'
    extension: 'json'
    create: true
    slug: '{{title}}'
    fields:
      - { label: Date, name: date, widget: date }
      - { label: Title, name: title, widget: string }
      - {
          label: Slug,
          name: slug,
          widget: string,
          pattern:
            [
              '^[a-z0-9]+(?:-[a-z0-9]+)*$',
              'Only lowercase characters, numbers and `-` are allowed. Moreover `-` must not be the first or the last character',
            ],
        }
      - { label: Thumbnail, name: thumbnail, widget: image }
      - { label: Body, name: body, widget: markdown }

  - name: 'banner' # Used in routes, e.g., /admin/collections/blog
    label: 'Banner' # Used in the UI
    files:
      - name: 'banner-en'
        label: EN
        file: 'data/banner_en.json'
        format: 'json'
        extension: 'json'
        fields:
          - { label: Message, name: message_en, widget: string }
          - { name: link, widget: string }

media_folder: 'src/images/uploads'

public_folder: 'images/uploads'

publish_mode: editorial_workflow
